[package]
name = "primes_multithreading"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

