[package]
name = "zlw"
version = "0.1.0"
edition = "2021"
flate2 = "1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.30"
